d1 = read.table("dap_sss_pip_vs_truth.dat")
fv = seq(0.0,0.9,0.1)
fv[1]=1e-4
tv = seq(0.1,1,0.1)
pv = sapply(1:10,function(x) mean(d1$V4[d1$V3>=fv[x]&d1$V3<tv[x]]))
mv = sapply(1:10, function(x) mean(d1$V3[d1$V3>=fv[x]&d1$V3<tv[x]]))
pdf(file="dap_sss_calibration.pdf", height=8, width=7.5,bg="white")
plot(mv ~ pv, ylab="Mean PIP", xlab = "True frequency",pch=16,cex=0.8,xlim=c(0,1),ylim=c(0,1),main="DAP-G (sufficient summary stats)")
abline(0,1,lty=2,col="blue")
dev.off()


d2 = read.table("fm_pip_vs_truth.dat")
pv = sapply(1:10,function(x) mean(d2$V4[d2$V3>=fv[x]&d2$V3<tv[x]]))
mv = sapply(1:10, function(x) mean(d2$V3[d2$V3>=fv[x]&d2$V3<tv[x]]))
pdf(file="fm_calibration.pdf", height=8, width=7.5,bg="white")
plot(mv ~ pv, ylab="Mean PIP", xlab = "True frequency",pch=16,cex=0.8,xlim=c(0,1),ylim=c(0,1), main="FINEMAP")
abline(0,1,lty=2,col="green")

dev.off()
d3 = read.table("dap_z_pip_vs_truth.dat")
fv = seq(0.0,0.9,0.1)
fv[1]=1e-4
tv = seq(0.1,1,0.1)
pv = sapply(1:10,function(x) mean(d3$V4[d3$V3>=fv[x]&d3$V3<tv[x]]))
mv = sapply(1:10, function(x) mean(d3$V3[d3$V3>=fv[x]&d3$V3<tv[x]]))
pdf(file="dap_z_calibration.pdf", height=8, width=7.5,bg="white")
plot(mv ~ pv, ylab="Mean PIP", xlab = "True frequency",pch=16,cex=0.8,xlim=c(0,1),ylim=c(0,1), main="DAP-G (z-scores)")
abline(0,1,lty=2,col="red")
dev.off()
