# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dap_main <- function(input_format, arg, quiet) {
    .Call(`_dap_dap_main`, input_format, arg, quiet)
}

read_sbams <- function(data_file) {
    .Call(`_dap_read_sbams`, data_file)
}

extract_sbams <- function(arg) {
    .Call(`_dap_extract_sbams`, arg)
}

