# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dap_main <- function(arg, quiet) {
    .Call(`_dap_dap_main`, arg, quiet)
}

dap_sbams <- function(x, y, normalize, arg, quiet, phenoname) {
    .Call(`_dap_dap_sbams`, x, y, normalize, arg, quiet, phenoname)
}

read_sbams <- function(data_file) {
    .Call(`_dap_read_sbams`, data_file)
}

