finemap --sss --in-files finemap_data/data --regions 1
finemap --sss --in-files finemap_data/data --regions 10
finemap --sss --in-files finemap_data/data --regions 100
finemap --sss --in-files finemap_data/data --regions 1000
finemap --sss --in-files finemap_data/data --regions 101
finemap --sss --in-files finemap_data/data --regions 102
finemap --sss --in-files finemap_data/data --regions 103
finemap --sss --in-files finemap_data/data --regions 104
finemap --sss --in-files finemap_data/data --regions 105
finemap --sss --in-files finemap_data/data --regions 106
finemap --sss --in-files finemap_data/data --regions 107
finemap --sss --in-files finemap_data/data --regions 108
finemap --sss --in-files finemap_data/data --regions 109
finemap --sss --in-files finemap_data/data --regions 11
finemap --sss --in-files finemap_data/data --regions 110
finemap --sss --in-files finemap_data/data --regions 111
finemap --sss --in-files finemap_data/data --regions 112
finemap --sss --in-files finemap_data/data --regions 113
finemap --sss --in-files finemap_data/data --regions 114
finemap --sss --in-files finemap_data/data --regions 115
finemap --sss --in-files finemap_data/data --regions 116
finemap --sss --in-files finemap_data/data --regions 117
finemap --sss --in-files finemap_data/data --regions 118
finemap --sss --in-files finemap_data/data --regions 119
finemap --sss --in-files finemap_data/data --regions 12
finemap --sss --in-files finemap_data/data --regions 120
finemap --sss --in-files finemap_data/data --regions 121
finemap --sss --in-files finemap_data/data --regions 122
finemap --sss --in-files finemap_data/data --regions 123
finemap --sss --in-files finemap_data/data --regions 124
finemap --sss --in-files finemap_data/data --regions 125
finemap --sss --in-files finemap_data/data --regions 126
finemap --sss --in-files finemap_data/data --regions 127
finemap --sss --in-files finemap_data/data --regions 128
finemap --sss --in-files finemap_data/data --regions 129
finemap --sss --in-files finemap_data/data --regions 13
finemap --sss --in-files finemap_data/data --regions 130
finemap --sss --in-files finemap_data/data --regions 131
finemap --sss --in-files finemap_data/data --regions 132
finemap --sss --in-files finemap_data/data --regions 133
finemap --sss --in-files finemap_data/data --regions 134
finemap --sss --in-files finemap_data/data --regions 135
finemap --sss --in-files finemap_data/data --regions 136
finemap --sss --in-files finemap_data/data --regions 137
finemap --sss --in-files finemap_data/data --regions 138
finemap --sss --in-files finemap_data/data --regions 139
finemap --sss --in-files finemap_data/data --regions 14
finemap --sss --in-files finemap_data/data --regions 140
finemap --sss --in-files finemap_data/data --regions 141
finemap --sss --in-files finemap_data/data --regions 142
finemap --sss --in-files finemap_data/data --regions 143
finemap --sss --in-files finemap_data/data --regions 144
finemap --sss --in-files finemap_data/data --regions 145
finemap --sss --in-files finemap_data/data --regions 146
finemap --sss --in-files finemap_data/data --regions 147
finemap --sss --in-files finemap_data/data --regions 148
finemap --sss --in-files finemap_data/data --regions 149
finemap --sss --in-files finemap_data/data --regions 15
finemap --sss --in-files finemap_data/data --regions 150
finemap --sss --in-files finemap_data/data --regions 151
finemap --sss --in-files finemap_data/data --regions 152
finemap --sss --in-files finemap_data/data --regions 153
finemap --sss --in-files finemap_data/data --regions 154
finemap --sss --in-files finemap_data/data --regions 155
finemap --sss --in-files finemap_data/data --regions 156
finemap --sss --in-files finemap_data/data --regions 157
finemap --sss --in-files finemap_data/data --regions 158
finemap --sss --in-files finemap_data/data --regions 159
finemap --sss --in-files finemap_data/data --regions 16
finemap --sss --in-files finemap_data/data --regions 160
finemap --sss --in-files finemap_data/data --regions 161
finemap --sss --in-files finemap_data/data --regions 162
finemap --sss --in-files finemap_data/data --regions 163
finemap --sss --in-files finemap_data/data --regions 164
finemap --sss --in-files finemap_data/data --regions 165
finemap --sss --in-files finemap_data/data --regions 166
finemap --sss --in-files finemap_data/data --regions 167
finemap --sss --in-files finemap_data/data --regions 168
finemap --sss --in-files finemap_data/data --regions 169
finemap --sss --in-files finemap_data/data --regions 17
finemap --sss --in-files finemap_data/data --regions 170
finemap --sss --in-files finemap_data/data --regions 171
finemap --sss --in-files finemap_data/data --regions 172
finemap --sss --in-files finemap_data/data --regions 173
finemap --sss --in-files finemap_data/data --regions 174
finemap --sss --in-files finemap_data/data --regions 175
finemap --sss --in-files finemap_data/data --regions 176
finemap --sss --in-files finemap_data/data --regions 177
finemap --sss --in-files finemap_data/data --regions 178
finemap --sss --in-files finemap_data/data --regions 179
finemap --sss --in-files finemap_data/data --regions 18
finemap --sss --in-files finemap_data/data --regions 180
finemap --sss --in-files finemap_data/data --regions 181
finemap --sss --in-files finemap_data/data --regions 182
finemap --sss --in-files finemap_data/data --regions 183
finemap --sss --in-files finemap_data/data --regions 184
finemap --sss --in-files finemap_data/data --regions 185
finemap --sss --in-files finemap_data/data --regions 186
finemap --sss --in-files finemap_data/data --regions 187
finemap --sss --in-files finemap_data/data --regions 188
finemap --sss --in-files finemap_data/data --regions 189
finemap --sss --in-files finemap_data/data --regions 19
finemap --sss --in-files finemap_data/data --regions 190
finemap --sss --in-files finemap_data/data --regions 191
finemap --sss --in-files finemap_data/data --regions 192
finemap --sss --in-files finemap_data/data --regions 193
finemap --sss --in-files finemap_data/data --regions 194
finemap --sss --in-files finemap_data/data --regions 195
finemap --sss --in-files finemap_data/data --regions 196
finemap --sss --in-files finemap_data/data --regions 197
finemap --sss --in-files finemap_data/data --regions 198
finemap --sss --in-files finemap_data/data --regions 199
finemap --sss --in-files finemap_data/data --regions 2
finemap --sss --in-files finemap_data/data --regions 20
finemap --sss --in-files finemap_data/data --regions 200
finemap --sss --in-files finemap_data/data --regions 201
finemap --sss --in-files finemap_data/data --regions 202
finemap --sss --in-files finemap_data/data --regions 203
finemap --sss --in-files finemap_data/data --regions 204
finemap --sss --in-files finemap_data/data --regions 205
finemap --sss --in-files finemap_data/data --regions 206
finemap --sss --in-files finemap_data/data --regions 207
finemap --sss --in-files finemap_data/data --regions 208
finemap --sss --in-files finemap_data/data --regions 209
finemap --sss --in-files finemap_data/data --regions 21
finemap --sss --in-files finemap_data/data --regions 210
finemap --sss --in-files finemap_data/data --regions 211
finemap --sss --in-files finemap_data/data --regions 212
finemap --sss --in-files finemap_data/data --regions 213
finemap --sss --in-files finemap_data/data --regions 214
finemap --sss --in-files finemap_data/data --regions 215
finemap --sss --in-files finemap_data/data --regions 216
finemap --sss --in-files finemap_data/data --regions 217
finemap --sss --in-files finemap_data/data --regions 218
finemap --sss --in-files finemap_data/data --regions 219
finemap --sss --in-files finemap_data/data --regions 22
finemap --sss --in-files finemap_data/data --regions 220
finemap --sss --in-files finemap_data/data --regions 221
finemap --sss --in-files finemap_data/data --regions 222
finemap --sss --in-files finemap_data/data --regions 223
finemap --sss --in-files finemap_data/data --regions 224
finemap --sss --in-files finemap_data/data --regions 225
finemap --sss --in-files finemap_data/data --regions 226
finemap --sss --in-files finemap_data/data --regions 227
finemap --sss --in-files finemap_data/data --regions 228
finemap --sss --in-files finemap_data/data --regions 229
finemap --sss --in-files finemap_data/data --regions 23
finemap --sss --in-files finemap_data/data --regions 230
finemap --sss --in-files finemap_data/data --regions 231
finemap --sss --in-files finemap_data/data --regions 232
finemap --sss --in-files finemap_data/data --regions 233
finemap --sss --in-files finemap_data/data --regions 234
finemap --sss --in-files finemap_data/data --regions 235
finemap --sss --in-files finemap_data/data --regions 236
finemap --sss --in-files finemap_data/data --regions 237
finemap --sss --in-files finemap_data/data --regions 238
finemap --sss --in-files finemap_data/data --regions 239
finemap --sss --in-files finemap_data/data --regions 24
finemap --sss --in-files finemap_data/data --regions 240
finemap --sss --in-files finemap_data/data --regions 241
finemap --sss --in-files finemap_data/data --regions 242
finemap --sss --in-files finemap_data/data --regions 243
finemap --sss --in-files finemap_data/data --regions 244
finemap --sss --in-files finemap_data/data --regions 245
finemap --sss --in-files finemap_data/data --regions 246
finemap --sss --in-files finemap_data/data --regions 247
finemap --sss --in-files finemap_data/data --regions 248
finemap --sss --in-files finemap_data/data --regions 249
finemap --sss --in-files finemap_data/data --regions 25
finemap --sss --in-files finemap_data/data --regions 250
finemap --sss --in-files finemap_data/data --regions 251
finemap --sss --in-files finemap_data/data --regions 252
finemap --sss --in-files finemap_data/data --regions 253
finemap --sss --in-files finemap_data/data --regions 254
finemap --sss --in-files finemap_data/data --regions 255
finemap --sss --in-files finemap_data/data --regions 256
finemap --sss --in-files finemap_data/data --regions 257
finemap --sss --in-files finemap_data/data --regions 258
finemap --sss --in-files finemap_data/data --regions 259
finemap --sss --in-files finemap_data/data --regions 26
finemap --sss --in-files finemap_data/data --regions 260
finemap --sss --in-files finemap_data/data --regions 261
finemap --sss --in-files finemap_data/data --regions 262
finemap --sss --in-files finemap_data/data --regions 263
finemap --sss --in-files finemap_data/data --regions 264
finemap --sss --in-files finemap_data/data --regions 265
finemap --sss --in-files finemap_data/data --regions 266
finemap --sss --in-files finemap_data/data --regions 267
finemap --sss --in-files finemap_data/data --regions 268
finemap --sss --in-files finemap_data/data --regions 269
finemap --sss --in-files finemap_data/data --regions 27
finemap --sss --in-files finemap_data/data --regions 270
finemap --sss --in-files finemap_data/data --regions 271
finemap --sss --in-files finemap_data/data --regions 272
finemap --sss --in-files finemap_data/data --regions 273
finemap --sss --in-files finemap_data/data --regions 274
finemap --sss --in-files finemap_data/data --regions 275
finemap --sss --in-files finemap_data/data --regions 276
finemap --sss --in-files finemap_data/data --regions 277
finemap --sss --in-files finemap_data/data --regions 278
finemap --sss --in-files finemap_data/data --regions 279
finemap --sss --in-files finemap_data/data --regions 28
finemap --sss --in-files finemap_data/data --regions 280
finemap --sss --in-files finemap_data/data --regions 281
finemap --sss --in-files finemap_data/data --regions 282
finemap --sss --in-files finemap_data/data --regions 283
finemap --sss --in-files finemap_data/data --regions 284
finemap --sss --in-files finemap_data/data --regions 285
finemap --sss --in-files finemap_data/data --regions 286
finemap --sss --in-files finemap_data/data --regions 287
finemap --sss --in-files finemap_data/data --regions 288
finemap --sss --in-files finemap_data/data --regions 289
finemap --sss --in-files finemap_data/data --regions 29
finemap --sss --in-files finemap_data/data --regions 290
finemap --sss --in-files finemap_data/data --regions 291
finemap --sss --in-files finemap_data/data --regions 292
finemap --sss --in-files finemap_data/data --regions 293
finemap --sss --in-files finemap_data/data --regions 294
finemap --sss --in-files finemap_data/data --regions 295
finemap --sss --in-files finemap_data/data --regions 296
finemap --sss --in-files finemap_data/data --regions 297
finemap --sss --in-files finemap_data/data --regions 298
finemap --sss --in-files finemap_data/data --regions 299
finemap --sss --in-files finemap_data/data --regions 3
finemap --sss --in-files finemap_data/data --regions 30
finemap --sss --in-files finemap_data/data --regions 300
finemap --sss --in-files finemap_data/data --regions 301
finemap --sss --in-files finemap_data/data --regions 302
finemap --sss --in-files finemap_data/data --regions 303
finemap --sss --in-files finemap_data/data --regions 304
finemap --sss --in-files finemap_data/data --regions 305
finemap --sss --in-files finemap_data/data --regions 306
finemap --sss --in-files finemap_data/data --regions 307
finemap --sss --in-files finemap_data/data --regions 308
finemap --sss --in-files finemap_data/data --regions 309
finemap --sss --in-files finemap_data/data --regions 31
finemap --sss --in-files finemap_data/data --regions 310
finemap --sss --in-files finemap_data/data --regions 311
finemap --sss --in-files finemap_data/data --regions 312
finemap --sss --in-files finemap_data/data --regions 313
finemap --sss --in-files finemap_data/data --regions 314
finemap --sss --in-files finemap_data/data --regions 315
finemap --sss --in-files finemap_data/data --regions 316
finemap --sss --in-files finemap_data/data --regions 317
finemap --sss --in-files finemap_data/data --regions 318
finemap --sss --in-files finemap_data/data --regions 319
finemap --sss --in-files finemap_data/data --regions 32
finemap --sss --in-files finemap_data/data --regions 320
finemap --sss --in-files finemap_data/data --regions 321
finemap --sss --in-files finemap_data/data --regions 322
finemap --sss --in-files finemap_data/data --regions 323
finemap --sss --in-files finemap_data/data --regions 324
finemap --sss --in-files finemap_data/data --regions 325
finemap --sss --in-files finemap_data/data --regions 326
finemap --sss --in-files finemap_data/data --regions 327
finemap --sss --in-files finemap_data/data --regions 328
finemap --sss --in-files finemap_data/data --regions 329
finemap --sss --in-files finemap_data/data --regions 33
finemap --sss --in-files finemap_data/data --regions 330
finemap --sss --in-files finemap_data/data --regions 331
finemap --sss --in-files finemap_data/data --regions 332
finemap --sss --in-files finemap_data/data --regions 333
finemap --sss --in-files finemap_data/data --regions 334
finemap --sss --in-files finemap_data/data --regions 335
finemap --sss --in-files finemap_data/data --regions 336
finemap --sss --in-files finemap_data/data --regions 337
finemap --sss --in-files finemap_data/data --regions 338
finemap --sss --in-files finemap_data/data --regions 339
finemap --sss --in-files finemap_data/data --regions 34
finemap --sss --in-files finemap_data/data --regions 340
finemap --sss --in-files finemap_data/data --regions 341
finemap --sss --in-files finemap_data/data --regions 342
finemap --sss --in-files finemap_data/data --regions 343
finemap --sss --in-files finemap_data/data --regions 344
finemap --sss --in-files finemap_data/data --regions 345
finemap --sss --in-files finemap_data/data --regions 346
finemap --sss --in-files finemap_data/data --regions 347
finemap --sss --in-files finemap_data/data --regions 348
finemap --sss --in-files finemap_data/data --regions 349
finemap --sss --in-files finemap_data/data --regions 35
finemap --sss --in-files finemap_data/data --regions 350
finemap --sss --in-files finemap_data/data --regions 351
finemap --sss --in-files finemap_data/data --regions 352
finemap --sss --in-files finemap_data/data --regions 353
finemap --sss --in-files finemap_data/data --regions 354
finemap --sss --in-files finemap_data/data --regions 355
finemap --sss --in-files finemap_data/data --regions 356
finemap --sss --in-files finemap_data/data --regions 357
finemap --sss --in-files finemap_data/data --regions 358
finemap --sss --in-files finemap_data/data --regions 359
finemap --sss --in-files finemap_data/data --regions 36
finemap --sss --in-files finemap_data/data --regions 360
finemap --sss --in-files finemap_data/data --regions 361
finemap --sss --in-files finemap_data/data --regions 362
finemap --sss --in-files finemap_data/data --regions 363
finemap --sss --in-files finemap_data/data --regions 364
finemap --sss --in-files finemap_data/data --regions 365
finemap --sss --in-files finemap_data/data --regions 366
finemap --sss --in-files finemap_data/data --regions 367
finemap --sss --in-files finemap_data/data --regions 368
finemap --sss --in-files finemap_data/data --regions 369
finemap --sss --in-files finemap_data/data --regions 37
finemap --sss --in-files finemap_data/data --regions 370
finemap --sss --in-files finemap_data/data --regions 371
finemap --sss --in-files finemap_data/data --regions 372
finemap --sss --in-files finemap_data/data --regions 373
finemap --sss --in-files finemap_data/data --regions 374
finemap --sss --in-files finemap_data/data --regions 375
finemap --sss --in-files finemap_data/data --regions 376
finemap --sss --in-files finemap_data/data --regions 377
finemap --sss --in-files finemap_data/data --regions 378
finemap --sss --in-files finemap_data/data --regions 379
finemap --sss --in-files finemap_data/data --regions 38
finemap --sss --in-files finemap_data/data --regions 380
finemap --sss --in-files finemap_data/data --regions 381
finemap --sss --in-files finemap_data/data --regions 382
finemap --sss --in-files finemap_data/data --regions 383
finemap --sss --in-files finemap_data/data --regions 384
finemap --sss --in-files finemap_data/data --regions 385
finemap --sss --in-files finemap_data/data --regions 386
finemap --sss --in-files finemap_data/data --regions 387
finemap --sss --in-files finemap_data/data --regions 388
finemap --sss --in-files finemap_data/data --regions 389
finemap --sss --in-files finemap_data/data --regions 39
finemap --sss --in-files finemap_data/data --regions 390
finemap --sss --in-files finemap_data/data --regions 391
finemap --sss --in-files finemap_data/data --regions 392
finemap --sss --in-files finemap_data/data --regions 393
finemap --sss --in-files finemap_data/data --regions 394
finemap --sss --in-files finemap_data/data --regions 395
finemap --sss --in-files finemap_data/data --regions 396
finemap --sss --in-files finemap_data/data --regions 397
finemap --sss --in-files finemap_data/data --regions 398
finemap --sss --in-files finemap_data/data --regions 399
finemap --sss --in-files finemap_data/data --regions 4
finemap --sss --in-files finemap_data/data --regions 40
finemap --sss --in-files finemap_data/data --regions 400
finemap --sss --in-files finemap_data/data --regions 401
finemap --sss --in-files finemap_data/data --regions 402
finemap --sss --in-files finemap_data/data --regions 403
finemap --sss --in-files finemap_data/data --regions 404
finemap --sss --in-files finemap_data/data --regions 405
finemap --sss --in-files finemap_data/data --regions 406
finemap --sss --in-files finemap_data/data --regions 407
finemap --sss --in-files finemap_data/data --regions 408
finemap --sss --in-files finemap_data/data --regions 409
finemap --sss --in-files finemap_data/data --regions 41
finemap --sss --in-files finemap_data/data --regions 410
finemap --sss --in-files finemap_data/data --regions 411
finemap --sss --in-files finemap_data/data --regions 412
finemap --sss --in-files finemap_data/data --regions 413
finemap --sss --in-files finemap_data/data --regions 414
finemap --sss --in-files finemap_data/data --regions 415
finemap --sss --in-files finemap_data/data --regions 416
finemap --sss --in-files finemap_data/data --regions 417
finemap --sss --in-files finemap_data/data --regions 418
finemap --sss --in-files finemap_data/data --regions 419
finemap --sss --in-files finemap_data/data --regions 42
finemap --sss --in-files finemap_data/data --regions 420
finemap --sss --in-files finemap_data/data --regions 421
finemap --sss --in-files finemap_data/data --regions 422
finemap --sss --in-files finemap_data/data --regions 423
finemap --sss --in-files finemap_data/data --regions 424
finemap --sss --in-files finemap_data/data --regions 425
finemap --sss --in-files finemap_data/data --regions 426
finemap --sss --in-files finemap_data/data --regions 427
finemap --sss --in-files finemap_data/data --regions 428
finemap --sss --in-files finemap_data/data --regions 429
finemap --sss --in-files finemap_data/data --regions 43
finemap --sss --in-files finemap_data/data --regions 430
finemap --sss --in-files finemap_data/data --regions 431
finemap --sss --in-files finemap_data/data --regions 432
finemap --sss --in-files finemap_data/data --regions 433
finemap --sss --in-files finemap_data/data --regions 434
finemap --sss --in-files finemap_data/data --regions 435
finemap --sss --in-files finemap_data/data --regions 436
finemap --sss --in-files finemap_data/data --regions 437
finemap --sss --in-files finemap_data/data --regions 438
finemap --sss --in-files finemap_data/data --regions 439
finemap --sss --in-files finemap_data/data --regions 44
finemap --sss --in-files finemap_data/data --regions 440
finemap --sss --in-files finemap_data/data --regions 441
finemap --sss --in-files finemap_data/data --regions 442
finemap --sss --in-files finemap_data/data --regions 443
finemap --sss --in-files finemap_data/data --regions 444
finemap --sss --in-files finemap_data/data --regions 445
finemap --sss --in-files finemap_data/data --regions 446
finemap --sss --in-files finemap_data/data --regions 447
finemap --sss --in-files finemap_data/data --regions 448
finemap --sss --in-files finemap_data/data --regions 449
finemap --sss --in-files finemap_data/data --regions 45
finemap --sss --in-files finemap_data/data --regions 450
finemap --sss --in-files finemap_data/data --regions 451
finemap --sss --in-files finemap_data/data --regions 452
finemap --sss --in-files finemap_data/data --regions 453
finemap --sss --in-files finemap_data/data --regions 454
finemap --sss --in-files finemap_data/data --regions 455
finemap --sss --in-files finemap_data/data --regions 456
finemap --sss --in-files finemap_data/data --regions 457
finemap --sss --in-files finemap_data/data --regions 458
finemap --sss --in-files finemap_data/data --regions 459
finemap --sss --in-files finemap_data/data --regions 46
finemap --sss --in-files finemap_data/data --regions 460
finemap --sss --in-files finemap_data/data --regions 461
finemap --sss --in-files finemap_data/data --regions 462
finemap --sss --in-files finemap_data/data --regions 463
finemap --sss --in-files finemap_data/data --regions 464
finemap --sss --in-files finemap_data/data --regions 465
finemap --sss --in-files finemap_data/data --regions 466
finemap --sss --in-files finemap_data/data --regions 467
finemap --sss --in-files finemap_data/data --regions 468
finemap --sss --in-files finemap_data/data --regions 469
finemap --sss --in-files finemap_data/data --regions 47
finemap --sss --in-files finemap_data/data --regions 470
finemap --sss --in-files finemap_data/data --regions 471
finemap --sss --in-files finemap_data/data --regions 472
finemap --sss --in-files finemap_data/data --regions 473
finemap --sss --in-files finemap_data/data --regions 474
finemap --sss --in-files finemap_data/data --regions 475
finemap --sss --in-files finemap_data/data --regions 476
finemap --sss --in-files finemap_data/data --regions 477
finemap --sss --in-files finemap_data/data --regions 478
finemap --sss --in-files finemap_data/data --regions 479
finemap --sss --in-files finemap_data/data --regions 48
finemap --sss --in-files finemap_data/data --regions 480
finemap --sss --in-files finemap_data/data --regions 481
finemap --sss --in-files finemap_data/data --regions 482
finemap --sss --in-files finemap_data/data --regions 483
finemap --sss --in-files finemap_data/data --regions 484
finemap --sss --in-files finemap_data/data --regions 485
finemap --sss --in-files finemap_data/data --regions 486
finemap --sss --in-files finemap_data/data --regions 487
finemap --sss --in-files finemap_data/data --regions 488
finemap --sss --in-files finemap_data/data --regions 489
finemap --sss --in-files finemap_data/data --regions 49
finemap --sss --in-files finemap_data/data --regions 490
finemap --sss --in-files finemap_data/data --regions 491
finemap --sss --in-files finemap_data/data --regions 492
finemap --sss --in-files finemap_data/data --regions 493
finemap --sss --in-files finemap_data/data --regions 494
finemap --sss --in-files finemap_data/data --regions 495
finemap --sss --in-files finemap_data/data --regions 496
finemap --sss --in-files finemap_data/data --regions 497
finemap --sss --in-files finemap_data/data --regions 498
finemap --sss --in-files finemap_data/data --regions 499
finemap --sss --in-files finemap_data/data --regions 5
finemap --sss --in-files finemap_data/data --regions 50
finemap --sss --in-files finemap_data/data --regions 500
finemap --sss --in-files finemap_data/data --regions 501
finemap --sss --in-files finemap_data/data --regions 502
finemap --sss --in-files finemap_data/data --regions 503
finemap --sss --in-files finemap_data/data --regions 504
finemap --sss --in-files finemap_data/data --regions 505
finemap --sss --in-files finemap_data/data --regions 506
finemap --sss --in-files finemap_data/data --regions 507
finemap --sss --in-files finemap_data/data --regions 508
finemap --sss --in-files finemap_data/data --regions 509
finemap --sss --in-files finemap_data/data --regions 51
finemap --sss --in-files finemap_data/data --regions 510
finemap --sss --in-files finemap_data/data --regions 511
finemap --sss --in-files finemap_data/data --regions 512
finemap --sss --in-files finemap_data/data --regions 513
finemap --sss --in-files finemap_data/data --regions 514
finemap --sss --in-files finemap_data/data --regions 515
finemap --sss --in-files finemap_data/data --regions 516
finemap --sss --in-files finemap_data/data --regions 517
finemap --sss --in-files finemap_data/data --regions 518
finemap --sss --in-files finemap_data/data --regions 519
finemap --sss --in-files finemap_data/data --regions 52
finemap --sss --in-files finemap_data/data --regions 520
finemap --sss --in-files finemap_data/data --regions 521
finemap --sss --in-files finemap_data/data --regions 522
finemap --sss --in-files finemap_data/data --regions 523
finemap --sss --in-files finemap_data/data --regions 524
finemap --sss --in-files finemap_data/data --regions 525
finemap --sss --in-files finemap_data/data --regions 526
finemap --sss --in-files finemap_data/data --regions 527
finemap --sss --in-files finemap_data/data --regions 528
finemap --sss --in-files finemap_data/data --regions 529
finemap --sss --in-files finemap_data/data --regions 53
finemap --sss --in-files finemap_data/data --regions 530
finemap --sss --in-files finemap_data/data --regions 531
finemap --sss --in-files finemap_data/data --regions 532
finemap --sss --in-files finemap_data/data --regions 533
finemap --sss --in-files finemap_data/data --regions 534
finemap --sss --in-files finemap_data/data --regions 535
finemap --sss --in-files finemap_data/data --regions 536
finemap --sss --in-files finemap_data/data --regions 537
finemap --sss --in-files finemap_data/data --regions 538
finemap --sss --in-files finemap_data/data --regions 539
finemap --sss --in-files finemap_data/data --regions 54
finemap --sss --in-files finemap_data/data --regions 540
finemap --sss --in-files finemap_data/data --regions 541
finemap --sss --in-files finemap_data/data --regions 542
finemap --sss --in-files finemap_data/data --regions 543
finemap --sss --in-files finemap_data/data --regions 544
finemap --sss --in-files finemap_data/data --regions 545
finemap --sss --in-files finemap_data/data --regions 546
finemap --sss --in-files finemap_data/data --regions 547
finemap --sss --in-files finemap_data/data --regions 548
finemap --sss --in-files finemap_data/data --regions 549
finemap --sss --in-files finemap_data/data --regions 55
finemap --sss --in-files finemap_data/data --regions 550
finemap --sss --in-files finemap_data/data --regions 551
finemap --sss --in-files finemap_data/data --regions 552
finemap --sss --in-files finemap_data/data --regions 553
finemap --sss --in-files finemap_data/data --regions 554
finemap --sss --in-files finemap_data/data --regions 555
finemap --sss --in-files finemap_data/data --regions 556
finemap --sss --in-files finemap_data/data --regions 557
finemap --sss --in-files finemap_data/data --regions 558
finemap --sss --in-files finemap_data/data --regions 559
finemap --sss --in-files finemap_data/data --regions 56
finemap --sss --in-files finemap_data/data --regions 560
finemap --sss --in-files finemap_data/data --regions 561
finemap --sss --in-files finemap_data/data --regions 562
finemap --sss --in-files finemap_data/data --regions 563
finemap --sss --in-files finemap_data/data --regions 564
finemap --sss --in-files finemap_data/data --regions 565
finemap --sss --in-files finemap_data/data --regions 566
finemap --sss --in-files finemap_data/data --regions 567
finemap --sss --in-files finemap_data/data --regions 568
finemap --sss --in-files finemap_data/data --regions 569
finemap --sss --in-files finemap_data/data --regions 57
finemap --sss --in-files finemap_data/data --regions 570
finemap --sss --in-files finemap_data/data --regions 571
finemap --sss --in-files finemap_data/data --regions 572
finemap --sss --in-files finemap_data/data --regions 573
finemap --sss --in-files finemap_data/data --regions 574
finemap --sss --in-files finemap_data/data --regions 575
finemap --sss --in-files finemap_data/data --regions 576
finemap --sss --in-files finemap_data/data --regions 577
finemap --sss --in-files finemap_data/data --regions 578
finemap --sss --in-files finemap_data/data --regions 579
finemap --sss --in-files finemap_data/data --regions 58
finemap --sss --in-files finemap_data/data --regions 580
finemap --sss --in-files finemap_data/data --regions 581
finemap --sss --in-files finemap_data/data --regions 582
finemap --sss --in-files finemap_data/data --regions 583
finemap --sss --in-files finemap_data/data --regions 584
finemap --sss --in-files finemap_data/data --regions 585
finemap --sss --in-files finemap_data/data --regions 586
finemap --sss --in-files finemap_data/data --regions 587
finemap --sss --in-files finemap_data/data --regions 588
finemap --sss --in-files finemap_data/data --regions 589
finemap --sss --in-files finemap_data/data --regions 59
finemap --sss --in-files finemap_data/data --regions 590
finemap --sss --in-files finemap_data/data --regions 591
finemap --sss --in-files finemap_data/data --regions 592
finemap --sss --in-files finemap_data/data --regions 593
finemap --sss --in-files finemap_data/data --regions 594
finemap --sss --in-files finemap_data/data --regions 595
finemap --sss --in-files finemap_data/data --regions 596
finemap --sss --in-files finemap_data/data --regions 597
finemap --sss --in-files finemap_data/data --regions 598
finemap --sss --in-files finemap_data/data --regions 599
finemap --sss --in-files finemap_data/data --regions 6
finemap --sss --in-files finemap_data/data --regions 60
finemap --sss --in-files finemap_data/data --regions 600
finemap --sss --in-files finemap_data/data --regions 601
finemap --sss --in-files finemap_data/data --regions 602
finemap --sss --in-files finemap_data/data --regions 603
finemap --sss --in-files finemap_data/data --regions 604
finemap --sss --in-files finemap_data/data --regions 605
finemap --sss --in-files finemap_data/data --regions 606
finemap --sss --in-files finemap_data/data --regions 607
finemap --sss --in-files finemap_data/data --regions 608
finemap --sss --in-files finemap_data/data --regions 609
finemap --sss --in-files finemap_data/data --regions 61
finemap --sss --in-files finemap_data/data --regions 610
finemap --sss --in-files finemap_data/data --regions 611
finemap --sss --in-files finemap_data/data --regions 612
finemap --sss --in-files finemap_data/data --regions 613
finemap --sss --in-files finemap_data/data --regions 614
finemap --sss --in-files finemap_data/data --regions 615
finemap --sss --in-files finemap_data/data --regions 616
finemap --sss --in-files finemap_data/data --regions 617
finemap --sss --in-files finemap_data/data --regions 618
finemap --sss --in-files finemap_data/data --regions 619
finemap --sss --in-files finemap_data/data --regions 62
finemap --sss --in-files finemap_data/data --regions 620
finemap --sss --in-files finemap_data/data --regions 621
finemap --sss --in-files finemap_data/data --regions 622
finemap --sss --in-files finemap_data/data --regions 623
finemap --sss --in-files finemap_data/data --regions 624
finemap --sss --in-files finemap_data/data --regions 625
finemap --sss --in-files finemap_data/data --regions 626
finemap --sss --in-files finemap_data/data --regions 627
finemap --sss --in-files finemap_data/data --regions 628
finemap --sss --in-files finemap_data/data --regions 629
finemap --sss --in-files finemap_data/data --regions 63
finemap --sss --in-files finemap_data/data --regions 630
finemap --sss --in-files finemap_data/data --regions 631
finemap --sss --in-files finemap_data/data --regions 632
finemap --sss --in-files finemap_data/data --regions 633
finemap --sss --in-files finemap_data/data --regions 634
finemap --sss --in-files finemap_data/data --regions 635
finemap --sss --in-files finemap_data/data --regions 636
finemap --sss --in-files finemap_data/data --regions 637
finemap --sss --in-files finemap_data/data --regions 638
finemap --sss --in-files finemap_data/data --regions 639
finemap --sss --in-files finemap_data/data --regions 64
finemap --sss --in-files finemap_data/data --regions 640
finemap --sss --in-files finemap_data/data --regions 641
finemap --sss --in-files finemap_data/data --regions 642
finemap --sss --in-files finemap_data/data --regions 643
finemap --sss --in-files finemap_data/data --regions 644
finemap --sss --in-files finemap_data/data --regions 645
finemap --sss --in-files finemap_data/data --regions 646
finemap --sss --in-files finemap_data/data --regions 647
finemap --sss --in-files finemap_data/data --regions 648
finemap --sss --in-files finemap_data/data --regions 649
finemap --sss --in-files finemap_data/data --regions 65
finemap --sss --in-files finemap_data/data --regions 650
finemap --sss --in-files finemap_data/data --regions 651
finemap --sss --in-files finemap_data/data --regions 652
finemap --sss --in-files finemap_data/data --regions 653
finemap --sss --in-files finemap_data/data --regions 654
finemap --sss --in-files finemap_data/data --regions 655
finemap --sss --in-files finemap_data/data --regions 656
finemap --sss --in-files finemap_data/data --regions 657
finemap --sss --in-files finemap_data/data --regions 658
finemap --sss --in-files finemap_data/data --regions 659
finemap --sss --in-files finemap_data/data --regions 66
finemap --sss --in-files finemap_data/data --regions 660
finemap --sss --in-files finemap_data/data --regions 661
finemap --sss --in-files finemap_data/data --regions 662
finemap --sss --in-files finemap_data/data --regions 663
finemap --sss --in-files finemap_data/data --regions 664
finemap --sss --in-files finemap_data/data --regions 665
finemap --sss --in-files finemap_data/data --regions 666
finemap --sss --in-files finemap_data/data --regions 667
finemap --sss --in-files finemap_data/data --regions 668
finemap --sss --in-files finemap_data/data --regions 669
finemap --sss --in-files finemap_data/data --regions 67
finemap --sss --in-files finemap_data/data --regions 670
finemap --sss --in-files finemap_data/data --regions 671
finemap --sss --in-files finemap_data/data --regions 672
finemap --sss --in-files finemap_data/data --regions 673
finemap --sss --in-files finemap_data/data --regions 674
finemap --sss --in-files finemap_data/data --regions 675
finemap --sss --in-files finemap_data/data --regions 676
finemap --sss --in-files finemap_data/data --regions 677
finemap --sss --in-files finemap_data/data --regions 678
finemap --sss --in-files finemap_data/data --regions 679
finemap --sss --in-files finemap_data/data --regions 68
finemap --sss --in-files finemap_data/data --regions 680
finemap --sss --in-files finemap_data/data --regions 681
finemap --sss --in-files finemap_data/data --regions 682
finemap --sss --in-files finemap_data/data --regions 683
finemap --sss --in-files finemap_data/data --regions 684
finemap --sss --in-files finemap_data/data --regions 685
finemap --sss --in-files finemap_data/data --regions 686
finemap --sss --in-files finemap_data/data --regions 687
finemap --sss --in-files finemap_data/data --regions 688
finemap --sss --in-files finemap_data/data --regions 689
finemap --sss --in-files finemap_data/data --regions 69
finemap --sss --in-files finemap_data/data --regions 690
finemap --sss --in-files finemap_data/data --regions 691
finemap --sss --in-files finemap_data/data --regions 692
finemap --sss --in-files finemap_data/data --regions 693
finemap --sss --in-files finemap_data/data --regions 694
finemap --sss --in-files finemap_data/data --regions 695
finemap --sss --in-files finemap_data/data --regions 696
finemap --sss --in-files finemap_data/data --regions 697
finemap --sss --in-files finemap_data/data --regions 698
finemap --sss --in-files finemap_data/data --regions 699
finemap --sss --in-files finemap_data/data --regions 7
finemap --sss --in-files finemap_data/data --regions 70
finemap --sss --in-files finemap_data/data --regions 700
finemap --sss --in-files finemap_data/data --regions 701
finemap --sss --in-files finemap_data/data --regions 702
finemap --sss --in-files finemap_data/data --regions 703
finemap --sss --in-files finemap_data/data --regions 704
finemap --sss --in-files finemap_data/data --regions 705
finemap --sss --in-files finemap_data/data --regions 706
finemap --sss --in-files finemap_data/data --regions 707
finemap --sss --in-files finemap_data/data --regions 708
finemap --sss --in-files finemap_data/data --regions 709
finemap --sss --in-files finemap_data/data --regions 71
finemap --sss --in-files finemap_data/data --regions 710
finemap --sss --in-files finemap_data/data --regions 711
finemap --sss --in-files finemap_data/data --regions 712
finemap --sss --in-files finemap_data/data --regions 713
finemap --sss --in-files finemap_data/data --regions 714
finemap --sss --in-files finemap_data/data --regions 715
finemap --sss --in-files finemap_data/data --regions 716
finemap --sss --in-files finemap_data/data --regions 717
finemap --sss --in-files finemap_data/data --regions 718
finemap --sss --in-files finemap_data/data --regions 719
finemap --sss --in-files finemap_data/data --regions 72
finemap --sss --in-files finemap_data/data --regions 720
finemap --sss --in-files finemap_data/data --regions 721
finemap --sss --in-files finemap_data/data --regions 722
finemap --sss --in-files finemap_data/data --regions 723
finemap --sss --in-files finemap_data/data --regions 724
finemap --sss --in-files finemap_data/data --regions 725
finemap --sss --in-files finemap_data/data --regions 726
finemap --sss --in-files finemap_data/data --regions 727
finemap --sss --in-files finemap_data/data --regions 728
finemap --sss --in-files finemap_data/data --regions 729
finemap --sss --in-files finemap_data/data --regions 73
finemap --sss --in-files finemap_data/data --regions 730
finemap --sss --in-files finemap_data/data --regions 731
finemap --sss --in-files finemap_data/data --regions 732
finemap --sss --in-files finemap_data/data --regions 733
finemap --sss --in-files finemap_data/data --regions 734
finemap --sss --in-files finemap_data/data --regions 735
finemap --sss --in-files finemap_data/data --regions 736
finemap --sss --in-files finemap_data/data --regions 737
finemap --sss --in-files finemap_data/data --regions 738
finemap --sss --in-files finemap_data/data --regions 739
finemap --sss --in-files finemap_data/data --regions 74
finemap --sss --in-files finemap_data/data --regions 740
finemap --sss --in-files finemap_data/data --regions 741
finemap --sss --in-files finemap_data/data --regions 742
finemap --sss --in-files finemap_data/data --regions 743
finemap --sss --in-files finemap_data/data --regions 744
finemap --sss --in-files finemap_data/data --regions 745
finemap --sss --in-files finemap_data/data --regions 746
finemap --sss --in-files finemap_data/data --regions 747
finemap --sss --in-files finemap_data/data --regions 748
finemap --sss --in-files finemap_data/data --regions 749
finemap --sss --in-files finemap_data/data --regions 75
finemap --sss --in-files finemap_data/data --regions 750
finemap --sss --in-files finemap_data/data --regions 751
finemap --sss --in-files finemap_data/data --regions 752
finemap --sss --in-files finemap_data/data --regions 753
finemap --sss --in-files finemap_data/data --regions 754
finemap --sss --in-files finemap_data/data --regions 755
finemap --sss --in-files finemap_data/data --regions 756
finemap --sss --in-files finemap_data/data --regions 757
finemap --sss --in-files finemap_data/data --regions 758
finemap --sss --in-files finemap_data/data --regions 759
finemap --sss --in-files finemap_data/data --regions 76
finemap --sss --in-files finemap_data/data --regions 760
finemap --sss --in-files finemap_data/data --regions 761
finemap --sss --in-files finemap_data/data --regions 762
finemap --sss --in-files finemap_data/data --regions 763
finemap --sss --in-files finemap_data/data --regions 764
finemap --sss --in-files finemap_data/data --regions 765
finemap --sss --in-files finemap_data/data --regions 766
finemap --sss --in-files finemap_data/data --regions 767
finemap --sss --in-files finemap_data/data --regions 768
finemap --sss --in-files finemap_data/data --regions 769
finemap --sss --in-files finemap_data/data --regions 77
finemap --sss --in-files finemap_data/data --regions 770
finemap --sss --in-files finemap_data/data --regions 771
finemap --sss --in-files finemap_data/data --regions 772
finemap --sss --in-files finemap_data/data --regions 773
finemap --sss --in-files finemap_data/data --regions 774
finemap --sss --in-files finemap_data/data --regions 775
finemap --sss --in-files finemap_data/data --regions 776
finemap --sss --in-files finemap_data/data --regions 777
finemap --sss --in-files finemap_data/data --regions 778
finemap --sss --in-files finemap_data/data --regions 779
finemap --sss --in-files finemap_data/data --regions 78
finemap --sss --in-files finemap_data/data --regions 780
finemap --sss --in-files finemap_data/data --regions 781
finemap --sss --in-files finemap_data/data --regions 782
finemap --sss --in-files finemap_data/data --regions 783
finemap --sss --in-files finemap_data/data --regions 784
finemap --sss --in-files finemap_data/data --regions 785
finemap --sss --in-files finemap_data/data --regions 786
finemap --sss --in-files finemap_data/data --regions 787
finemap --sss --in-files finemap_data/data --regions 788
finemap --sss --in-files finemap_data/data --regions 789
finemap --sss --in-files finemap_data/data --regions 79
finemap --sss --in-files finemap_data/data --regions 790
finemap --sss --in-files finemap_data/data --regions 791
finemap --sss --in-files finemap_data/data --regions 792
finemap --sss --in-files finemap_data/data --regions 793
finemap --sss --in-files finemap_data/data --regions 794
finemap --sss --in-files finemap_data/data --regions 795
finemap --sss --in-files finemap_data/data --regions 796
finemap --sss --in-files finemap_data/data --regions 797
finemap --sss --in-files finemap_data/data --regions 798
finemap --sss --in-files finemap_data/data --regions 799
finemap --sss --in-files finemap_data/data --regions 8
finemap --sss --in-files finemap_data/data --regions 80
finemap --sss --in-files finemap_data/data --regions 800
finemap --sss --in-files finemap_data/data --regions 801
finemap --sss --in-files finemap_data/data --regions 802
finemap --sss --in-files finemap_data/data --regions 803
finemap --sss --in-files finemap_data/data --regions 804
finemap --sss --in-files finemap_data/data --regions 805
finemap --sss --in-files finemap_data/data --regions 806
finemap --sss --in-files finemap_data/data --regions 807
finemap --sss --in-files finemap_data/data --regions 808
finemap --sss --in-files finemap_data/data --regions 809
finemap --sss --in-files finemap_data/data --regions 81
finemap --sss --in-files finemap_data/data --regions 810
finemap --sss --in-files finemap_data/data --regions 811
finemap --sss --in-files finemap_data/data --regions 812
finemap --sss --in-files finemap_data/data --regions 813
finemap --sss --in-files finemap_data/data --regions 814
finemap --sss --in-files finemap_data/data --regions 815
finemap --sss --in-files finemap_data/data --regions 816
finemap --sss --in-files finemap_data/data --regions 817
finemap --sss --in-files finemap_data/data --regions 818
finemap --sss --in-files finemap_data/data --regions 819
finemap --sss --in-files finemap_data/data --regions 82
finemap --sss --in-files finemap_data/data --regions 820
finemap --sss --in-files finemap_data/data --regions 821
finemap --sss --in-files finemap_data/data --regions 822
finemap --sss --in-files finemap_data/data --regions 823
finemap --sss --in-files finemap_data/data --regions 824
finemap --sss --in-files finemap_data/data --regions 825
finemap --sss --in-files finemap_data/data --regions 826
finemap --sss --in-files finemap_data/data --regions 827
finemap --sss --in-files finemap_data/data --regions 828
finemap --sss --in-files finemap_data/data --regions 829
finemap --sss --in-files finemap_data/data --regions 83
finemap --sss --in-files finemap_data/data --regions 830
finemap --sss --in-files finemap_data/data --regions 831
finemap --sss --in-files finemap_data/data --regions 832
finemap --sss --in-files finemap_data/data --regions 833
finemap --sss --in-files finemap_data/data --regions 834
finemap --sss --in-files finemap_data/data --regions 835
finemap --sss --in-files finemap_data/data --regions 836
finemap --sss --in-files finemap_data/data --regions 837
finemap --sss --in-files finemap_data/data --regions 838
finemap --sss --in-files finemap_data/data --regions 839
finemap --sss --in-files finemap_data/data --regions 84
finemap --sss --in-files finemap_data/data --regions 840
finemap --sss --in-files finemap_data/data --regions 841
finemap --sss --in-files finemap_data/data --regions 842
finemap --sss --in-files finemap_data/data --regions 843
finemap --sss --in-files finemap_data/data --regions 844
finemap --sss --in-files finemap_data/data --regions 845
finemap --sss --in-files finemap_data/data --regions 846
finemap --sss --in-files finemap_data/data --regions 847
finemap --sss --in-files finemap_data/data --regions 848
finemap --sss --in-files finemap_data/data --regions 849
finemap --sss --in-files finemap_data/data --regions 85
finemap --sss --in-files finemap_data/data --regions 850
finemap --sss --in-files finemap_data/data --regions 851
finemap --sss --in-files finemap_data/data --regions 852
finemap --sss --in-files finemap_data/data --regions 853
finemap --sss --in-files finemap_data/data --regions 854
finemap --sss --in-files finemap_data/data --regions 855
finemap --sss --in-files finemap_data/data --regions 856
finemap --sss --in-files finemap_data/data --regions 857
finemap --sss --in-files finemap_data/data --regions 858
finemap --sss --in-files finemap_data/data --regions 859
finemap --sss --in-files finemap_data/data --regions 86
finemap --sss --in-files finemap_data/data --regions 860
finemap --sss --in-files finemap_data/data --regions 861
finemap --sss --in-files finemap_data/data --regions 862
finemap --sss --in-files finemap_data/data --regions 863
finemap --sss --in-files finemap_data/data --regions 864
finemap --sss --in-files finemap_data/data --regions 865
finemap --sss --in-files finemap_data/data --regions 866
finemap --sss --in-files finemap_data/data --regions 867
finemap --sss --in-files finemap_data/data --regions 868
finemap --sss --in-files finemap_data/data --regions 869
finemap --sss --in-files finemap_data/data --regions 87
finemap --sss --in-files finemap_data/data --regions 870
finemap --sss --in-files finemap_data/data --regions 871
finemap --sss --in-files finemap_data/data --regions 872
finemap --sss --in-files finemap_data/data --regions 873
finemap --sss --in-files finemap_data/data --regions 874
finemap --sss --in-files finemap_data/data --regions 875
finemap --sss --in-files finemap_data/data --regions 876
finemap --sss --in-files finemap_data/data --regions 877
finemap --sss --in-files finemap_data/data --regions 878
finemap --sss --in-files finemap_data/data --regions 879
finemap --sss --in-files finemap_data/data --regions 88
finemap --sss --in-files finemap_data/data --regions 880
finemap --sss --in-files finemap_data/data --regions 881
finemap --sss --in-files finemap_data/data --regions 882
finemap --sss --in-files finemap_data/data --regions 883
finemap --sss --in-files finemap_data/data --regions 884
finemap --sss --in-files finemap_data/data --regions 885
finemap --sss --in-files finemap_data/data --regions 886
finemap --sss --in-files finemap_data/data --regions 887
finemap --sss --in-files finemap_data/data --regions 888
finemap --sss --in-files finemap_data/data --regions 889
finemap --sss --in-files finemap_data/data --regions 89
finemap --sss --in-files finemap_data/data --regions 890
finemap --sss --in-files finemap_data/data --regions 891
finemap --sss --in-files finemap_data/data --regions 892
finemap --sss --in-files finemap_data/data --regions 893
finemap --sss --in-files finemap_data/data --regions 894
finemap --sss --in-files finemap_data/data --regions 895
finemap --sss --in-files finemap_data/data --regions 896
finemap --sss --in-files finemap_data/data --regions 897
finemap --sss --in-files finemap_data/data --regions 898
finemap --sss --in-files finemap_data/data --regions 899
finemap --sss --in-files finemap_data/data --regions 9
finemap --sss --in-files finemap_data/data --regions 90
finemap --sss --in-files finemap_data/data --regions 900
finemap --sss --in-files finemap_data/data --regions 901
finemap --sss --in-files finemap_data/data --regions 902
finemap --sss --in-files finemap_data/data --regions 903
finemap --sss --in-files finemap_data/data --regions 904
finemap --sss --in-files finemap_data/data --regions 905
finemap --sss --in-files finemap_data/data --regions 906
finemap --sss --in-files finemap_data/data --regions 907
finemap --sss --in-files finemap_data/data --regions 908
finemap --sss --in-files finemap_data/data --regions 909
finemap --sss --in-files finemap_data/data --regions 91
finemap --sss --in-files finemap_data/data --regions 910
finemap --sss --in-files finemap_data/data --regions 911
finemap --sss --in-files finemap_data/data --regions 912
finemap --sss --in-files finemap_data/data --regions 913
finemap --sss --in-files finemap_data/data --regions 914
finemap --sss --in-files finemap_data/data --regions 915
finemap --sss --in-files finemap_data/data --regions 916
finemap --sss --in-files finemap_data/data --regions 917
finemap --sss --in-files finemap_data/data --regions 918
finemap --sss --in-files finemap_data/data --regions 919
finemap --sss --in-files finemap_data/data --regions 92
finemap --sss --in-files finemap_data/data --regions 920
finemap --sss --in-files finemap_data/data --regions 921
finemap --sss --in-files finemap_data/data --regions 922
finemap --sss --in-files finemap_data/data --regions 923
finemap --sss --in-files finemap_data/data --regions 924
finemap --sss --in-files finemap_data/data --regions 925
finemap --sss --in-files finemap_data/data --regions 926
finemap --sss --in-files finemap_data/data --regions 927
finemap --sss --in-files finemap_data/data --regions 928
finemap --sss --in-files finemap_data/data --regions 929
finemap --sss --in-files finemap_data/data --regions 93
finemap --sss --in-files finemap_data/data --regions 930
finemap --sss --in-files finemap_data/data --regions 931
finemap --sss --in-files finemap_data/data --regions 932
finemap --sss --in-files finemap_data/data --regions 933
finemap --sss --in-files finemap_data/data --regions 934
finemap --sss --in-files finemap_data/data --regions 935
finemap --sss --in-files finemap_data/data --regions 936
finemap --sss --in-files finemap_data/data --regions 937
finemap --sss --in-files finemap_data/data --regions 938
finemap --sss --in-files finemap_data/data --regions 939
finemap --sss --in-files finemap_data/data --regions 94
finemap --sss --in-files finemap_data/data --regions 940
finemap --sss --in-files finemap_data/data --regions 941
finemap --sss --in-files finemap_data/data --regions 942
finemap --sss --in-files finemap_data/data --regions 943
finemap --sss --in-files finemap_data/data --regions 944
finemap --sss --in-files finemap_data/data --regions 945
finemap --sss --in-files finemap_data/data --regions 946
finemap --sss --in-files finemap_data/data --regions 947
finemap --sss --in-files finemap_data/data --regions 948
finemap --sss --in-files finemap_data/data --regions 949
finemap --sss --in-files finemap_data/data --regions 95
finemap --sss --in-files finemap_data/data --regions 950
finemap --sss --in-files finemap_data/data --regions 951
finemap --sss --in-files finemap_data/data --regions 952
finemap --sss --in-files finemap_data/data --regions 953
finemap --sss --in-files finemap_data/data --regions 954
finemap --sss --in-files finemap_data/data --regions 955
finemap --sss --in-files finemap_data/data --regions 956
finemap --sss --in-files finemap_data/data --regions 957
finemap --sss --in-files finemap_data/data --regions 958
finemap --sss --in-files finemap_data/data --regions 959
finemap --sss --in-files finemap_data/data --regions 96
finemap --sss --in-files finemap_data/data --regions 960
finemap --sss --in-files finemap_data/data --regions 961
finemap --sss --in-files finemap_data/data --regions 962
finemap --sss --in-files finemap_data/data --regions 963
finemap --sss --in-files finemap_data/data --regions 964
finemap --sss --in-files finemap_data/data --regions 965
finemap --sss --in-files finemap_data/data --regions 966
finemap --sss --in-files finemap_data/data --regions 967
finemap --sss --in-files finemap_data/data --regions 968
finemap --sss --in-files finemap_data/data --regions 969
finemap --sss --in-files finemap_data/data --regions 97
finemap --sss --in-files finemap_data/data --regions 970
finemap --sss --in-files finemap_data/data --regions 971
finemap --sss --in-files finemap_data/data --regions 972
finemap --sss --in-files finemap_data/data --regions 973
finemap --sss --in-files finemap_data/data --regions 974
finemap --sss --in-files finemap_data/data --regions 975
finemap --sss --in-files finemap_data/data --regions 976
finemap --sss --in-files finemap_data/data --regions 977
finemap --sss --in-files finemap_data/data --regions 978
finemap --sss --in-files finemap_data/data --regions 979
finemap --sss --in-files finemap_data/data --regions 98
finemap --sss --in-files finemap_data/data --regions 980
finemap --sss --in-files finemap_data/data --regions 981
finemap --sss --in-files finemap_data/data --regions 982
finemap --sss --in-files finemap_data/data --regions 983
finemap --sss --in-files finemap_data/data --regions 984
finemap --sss --in-files finemap_data/data --regions 985
finemap --sss --in-files finemap_data/data --regions 986
finemap --sss --in-files finemap_data/data --regions 987
finemap --sss --in-files finemap_data/data --regions 988
finemap --sss --in-files finemap_data/data --regions 989
finemap --sss --in-files finemap_data/data --regions 99
finemap --sss --in-files finemap_data/data --regions 990
finemap --sss --in-files finemap_data/data --regions 991
finemap --sss --in-files finemap_data/data --regions 992
finemap --sss --in-files finemap_data/data --regions 993
finemap --sss --in-files finemap_data/data --regions 994
finemap --sss --in-files finemap_data/data --regions 995
finemap --sss --in-files finemap_data/data --regions 996
finemap --sss --in-files finemap_data/data --regions 997
finemap --sss --in-files finemap_data/data --regions 998
finemap --sss --in-files finemap_data/data --regions 999
